module.exports = {
  metadata: {
    source: "local-seed",
    note: "Data awal contoh. Perbarui file database/db.json setelah bot pertama kali dijalankan, atau ganti service data dengan API resmi.",
  },
  teams: [
    {
      id: "mexico",
      name: "Mexico",
      fifaCode: "MEX",
      group: "A",
      federation: "CONCACAF",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Salah satu tuan rumah Piala Dunia dengan tradisi kuat di fase grup.",
    },
    {
      id: "south-africa",
      name: "South Africa",
      fifaCode: "RSA",
      group: "A",
      federation: "CAF",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim nasional Afrika Selatan.",
    },
    {
      id: "united-states",
      name: "United States",
      fifaCode: "USA",
      group: "B",
      federation: "CONCACAF",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Salah satu tuan rumah Piala Dunia dengan skuad muda dan cepat.",
    },
    {
      id: "wales",
      name: "Wales",
      fifaCode: "WAL",
      group: "B",
      federation: "UEFA",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim nasional Wales.",
    },
    {
      id: "argentina",
      name: "Argentina",
      fifaCode: "ARG",
      group: "C",
      federation: "CONMEBOL",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Juara dunia yang dikenal dengan teknik dan lini serang kreatif.",
    },
    {
      id: "saudi-arabia",
      name: "Saudi Arabia",
      fifaCode: "KSA",
      group: "C",
      federation: "AFC",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim nasional Arab Saudi.",
    },
    {
      id: "france",
      name: "France",
      fifaCode: "FRA",
      group: "D",
      federation: "UEFA",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim elit Eropa dengan kedalaman skuad di hampir semua posisi.",
    },
    {
      id: "denmark",
      name: "Denmark",
      fifaCode: "DEN",
      group: "D",
      federation: "UEFA",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim nasional Denmark.",
    },
    {
      id: "brazil",
      name: "Brazil",
      fifaCode: "BRA",
      group: "E",
      federation: "CONMEBOL",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Pemilik tradisi Piala Dunia paling ikonik dengan gaya menyerang.",
    },
    {
      id: "serbia",
      name: "Serbia",
      fifaCode: "SRB",
      group: "E",
      federation: "UEFA",
      coach: "Belum diatur",
      captain: "Belum diatur",
      description: "Tim nasional Serbia.",
    },
  ],
  matches: [
    {
      id: "M001",
      stage: "Group Stage",
      group: "A",
      homeTeamId: "mexico",
      awayTeamId: "south-africa",
      kickoff: "2026-06-11T19:00:00.000Z",
      venue: "Estadio Azteca",
      status: "finished",
      homeScore: 2,
      awayScore: 1,
    },
    {
      id: "M002",
      stage: "Group Stage",
      group: "B",
      homeTeamId: "united-states",
      awayTeamId: "wales",
      kickoff: "2026-06-12T01:00:00.000Z",
      venue: "SoFi Stadium",
      status: "finished",
      homeScore: 1,
      awayScore: 1,
    },
    {
      id: "M003",
      stage: "Group Stage",
      group: "C",
      homeTeamId: "argentina",
      awayTeamId: "saudi-arabia",
      kickoff: "2026-06-14T19:00:00.000Z",
      venue: "MetLife Stadium",
      status: "scheduled",
      homeScore: null,
      awayScore: null,
    },
    {
      id: "M004",
      stage: "Group Stage",
      group: "D",
      homeTeamId: "france",
      awayTeamId: "denmark",
      kickoff: "2026-06-15T22:00:00.000Z",
      venue: "AT&T Stadium",
      status: "scheduled",
      homeScore: null,
      awayScore: null,
    },
    {
      id: "M005",
      stage: "Group Stage",
      group: "E",
      homeTeamId: "brazil",
      awayTeamId: "serbia",
      kickoff: "2026-06-16T01:00:00.000Z",
      venue: "Hard Rock Stadium",
      status: "scheduled",
      homeScore: null,
      awayScore: null,
    },
  ],
  standings: [
    {
      group: "A",
      teamId: "mexico",
      played: 1,
      won: 1,
      drawn: 0,
      lost: 0,
      goalsFor: 2,
      goalsAgainst: 1,
      points: 3,
    },
    {
      group: "A",
      teamId: "south-africa",
      played: 1,
      won: 0,
      drawn: 0,
      lost: 1,
      goalsFor: 1,
      goalsAgainst: 2,
      points: 0,
    },
    {
      group: "B",
      teamId: "united-states",
      played: 1,
      won: 0,
      drawn: 1,
      lost: 0,
      goalsFor: 1,
      goalsAgainst: 1,
      points: 1,
    },
    {
      group: "B",
      teamId: "wales",
      played: 1,
      won: 0,
      drawn: 1,
      lost: 0,
      goalsFor: 1,
      goalsAgainst: 1,
      points: 1,
    },
    {
      group: "C",
      teamId: "argentina",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
    {
      group: "C",
      teamId: "saudi-arabia",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
    {
      group: "D",
      teamId: "france",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
    {
      group: "D",
      teamId: "denmark",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
    {
      group: "E",
      teamId: "brazil",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
    {
      group: "E",
      teamId: "serbia",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
    },
  ],
  predictions: [],
  notificationLog: {
    matchReminders: [],
    resultNotifications: [],
  },
};
